### ISSUE TITLE
List of possible new features

### ISSUE THREAD

**Issue by stephan1827** [stephan1827/mappView-User#20]
- Add support for new B&R RFID reader 5E9030.29 to RFID branch

**Comment by mscheffauer** [comment]
Tested in customer application, following things could be added:

- A textgroup with all texts that are used is recommended for localization
- Renamed user "" to "" - here snippets combined with textgroup from mappView would be nice / especially when made multi-client capable
- an export possibility on a usb stick
- a possibility to determine default users, which cannot be renamed or deleted (maybe choosable)
- delete the password out of the password widgets via Eventbinding, when logging in, renaming, changing pw: otherwise an unauthorized person could intrude the system

**Comment by stephan1827** [comment]
Thx for the suggestions, I already implemented the last point. I thought about using text files but it would add quite a bit of extra files and configurations especially if there is no localization in place. The goal was to make the sample easy to import into an existing project. That is why I decided against text files for now.
