### ISSUE TITLE
PeterDoc

### ISSUE THREAD

**Issue by PeterDoc** [stephan1827/mappView-User#22]
Dear stephan1827,

very nice piece of program but during testing i found 2 problems:
1. 5A9020.43 type tags are not read because they have only 8 characters. But after changing the initialization change RFID.PAR.DataMinLen from 16 to 8 the data was obtained.
When logging in using RFID, the Active field displays a different user than the one read by RFID: Last message. And here I don't really know where to make corrections.
Regards, PeterDoc
![obraz](https://user-images.githubusercontent.com/124912038/222237908-5e4c61da-7de1-4268-ad59-b402a85829da.png)

**Comment by stephan1827** [comment]
I never tried the 5A9020.43, but I can add it to the list of readers so DataMinLen adjust automatically. The second issue is something that needs more investigation. What happens when you log out Dave first? Does Bob get logged in if no user was logged in before? What happens when you type in Bob as Username and then use the token data as Password. Does that work?

Stephan

**Comment by PeterDoc** [comment]
Hi Stephan1827

thank you for your reaction because I am at the stage of learning about the capabilities of B&R equipment. As for the second point, I think I moved something because when I removed Bob and created the account again correctly, everything started to work OK :).
PeterDoc

**Comment by stephan1827** [comment]
No worries, I will make some changes to the sample, so it can be adopted easier to the 5A9020.43 keys. Also keep in mind that there is a version 2 of this sample that utilizes the newer widgets that were introduced with mapp 5.17. I changed the starting page to show all 4 options.
